name: GPU integration CI pipeline

on:
  pull_request:

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-22.04
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2.3.6
        with:
          mode: start
          github-token: ${{ secrets.GH_TOKEN }}
          ec2-image-id: ${{ vars.AWS_EC2_IMAGE_ID }}
          ec2-instance-type: ${{ vars.AWS_EC2_INSTANCE_TYPE }}
          subnet-id: ${{ vars.AWS_DEFAULT_SUBNET_ID }}
          security-group-id: ${{ vars.AWS_SECURITY_GROUP_ID }}
  
  integration-tests:
    name: Run integration tests
    needs: [start-runner]
    runs-on: ${{ needs.start-runner.outputs.label }} 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Install microk8s
    #   run: |
    #     /bin/bash ./tests/integration/setup-microk8s.sh "1.28/stable"
    #     newgrp microk8s
    #   env:
    #     USER: "ubuntu"

    - name: Setup ssh key
      run: |
        mkdir -p ~/.ssh
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIblfuGliBWslSSGDZZ8au1VwGFqHHuyz5KBuHEdl3Ig Canonical ssh" > ~/.ssh/authorized_keys
    - name: Setup environment
      run: |
        sudo -E bash ./tests/integration/setup-environment.sh
      env:
        MICROK8S_CHANNEL: 1.28/stable

    - name: Setup microk8s
      run: sudo -E /bin/bash ./tests/integration/config-microk8s-gpu.sh
      env:
        MICROK8S_ADDONS: "storage dns rbac gpu minio"

    - name: Check microk8s status
      run: |
        sudo microk8s.status
        echo "here"
        ls /home/
        sudo snap install yq
        sudo snap alias microk8s.kubectl kubectl
        echo "h1"
        mkdir -p ~/.kube
        sudo chown -f -R ubuntu ~/.kube
        echo "h2"
        mkdir -p /home/ubuntu/.kube
        echo "h2.1"
        sudo chown -f -R ubuntu /home/ubuntu/.kube
        echo "h3"
        sudo microk8s config | tee ~/.kube/config
        echo "h4"
        sudo microk8s config | tee /home/ubuntu/.kube/config
        echo "h5"
        /bin/bash ./tests/integration/integration-tests-gpu.sh
        echo "End of the test :)"

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner 
      - integration-tests
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2.3.6
        with:
          mode: stop
          github-token: ${{ secrets.GH_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}